#### NumPy Arrays

In [2]:
my_list=[1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.13039698, 0.08989396, 0.77180046, 0.97101531, 0.0365363 ])

In [16]:
np.random.rand(5,5)

array([[0.68941236, 0.83242734, 0.62518197, 0.73570153, 0.95467481],
       [0.98468845, 0.58654544, 0.33388309, 0.51931051, 0.64137582],
       [0.07950355, 0.70855253, 0.12912694, 0.77315936, 0.13525355],
       [0.89880966, 0.66901513, 0.98637649, 0.41543176, 0.36900039],
       [0.39995408, 0.82469401, 0.8029269 , 0.02384184, 0.09622763]])

In [17]:
np.random.randn(2,2)

array([[-1.44015276,  0.72974078],
       [-2.04764469,  0.36648189]])

In [18]:
np.random.randint(1,100,10)

array([17,  1, 29, 45,  5, 69, 14, 55, 28,  8])

In [19]:
arr=np.arange(25)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr=np.random.randint(0,50,10)

In [22]:
ranarr

array([34,  4, 33, 47,  8, 10, 19, 36, 40,  8])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr

array([34,  4, 33, 47,  8, 10, 19, 36, 40,  8])

In [25]:
ranarr.max()

47

In [26]:
ranarr.min()

4

In [27]:
ranarr

array([34,  4, 33, 47,  8, 10, 19, 36, 40,  8])

In [28]:
ranarr.argmax()

3

In [29]:
ranarr.argmin()

1

In [30]:
arr=arr.reshape(5,5)

In [31]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.shape

(5, 5)

In [33]:
arr.dtype

dtype('int32')

In [44]:
arr_2d=np.arange(50).reshape(5,10)

In [46]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [60]:
arr_2d[3:5,0:2]

array([[30, 31],
       [40, 41]])